### ISSUE TITLE
Can't use library with esbuild 

### ISSUE THREAD

**Issue by SahaSaurav** [ilovepixelart/ts-express-swc#8]
**Describe the bug**
my project uses esbuild which seems to be incompatible with swc 

**To Reproduce**
install ts-express-swc in project that builds with esbuild, run build step to see following errors:
<img width="441" alt="esbuild_swc_issuepng" src="https://user-images.githubusercontent.com/32855889/235848433-749ae402-2e8b-4b7b-bda5-fde379209de7.png">

**Expected behavior**
Will this library not work with projects that use esbuild? Is there a workaround for this? 

**Desktop (please complete the following information):**
- OS: Windows 11

Let me know if any additional context is needed.

**Comment by ilovepixelart** [comment]
Hey @SahaSaurav ts-express-swc was intended to be used with **swc** not **esbuild**
Can you push example to GitHub and share the link with me, I'm trying to understand what exactly you trying to do

**Comment by SahaSaurav** [comment]
@ilovepixelart Im silly, I accidentally opened this issue on the wrong repository. You're correct, meant to open this on ts-migrate-mongoose
